### PR TITLE
feat: implement `fmt::Display` for `Footer`

### PR DESCRIPTION
**Pull request by jan-ferdinand**
This simplifies pattern matching on footers in downstream dependencies.

### CODE REVIEW

**Comment by epage** [comment]
> This simplifies pattern matching on footers in downstream dependencies.

While I'm fine with this change, I find this a bit confusing.  How does a `Display` impl affect pattern matching?

**Comment by jan-ferdinand** [comment]
It mostly means that the canonical string representation of a `Footer` lives here, and does not have to be replicated by whoever needs it. If you think this “improvement” is an indicator that I fundamentally misunderstand something about pattern matching, I'm happy to learn better ways. :slightly_smiling_face:

**Comment by epage** [comment]
In programming language, pattern matching usually refers to things like `match` arms having a structure to them that gets matched, see https://blog.rust-lang.org/inside-rust/2020/03/04/recent-future-pattern-matching-improvements.html

This is about reducing duplicated knowledge / making the API more ergonomic

**Comment by epage** [comment]
btw looks like there is a formatting issue to fix before merging

**Comment by jan-ferdinand** [comment]
Ah, true; I had regexes in mind, which also match on patterns. :relieved:

**Pull request merged**
